// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		double big = 0;
		double small = 0;
		for (int i=0 ; i<N ; i++)
		{
			double num = Math.random();
			if(num<=0.5)
			{
				small = small +1;
			}
			else
			{
				big = big +1;
			}
		}
		double max = (double)(Math.max(big, small));
		double min = (double)(Math.min(big, small));
		double ratio = min/max;

		System.out.println("> 0.5: "+(int) big + " times");
		System.out.println("<= 0.5: "+ (int) small + " times");
		System.out.println("Ratio: " + ratio);
	}
}
